CREATE TABLE STUDATA {
ID INT PRIMARY KEY NOT NULL,
NAME CHAR(50) NOT NULL,
MATHS INT NOT NULL,
SCIENCE INT NOT NULL,
ENGLISH INT NOT NULL,
HINDI INT NOT NULL,
SOCIAL_SCIENCE INT NOT NULL,
COMPUTER_SCIENCE INT NOT NULL,
MATHS_MAX INT NOT NULL,
SCIENCE_MAX INT NOT NULL,
ENGLISH_MAX INT NOT NULL,
HINDI_MAX INT NOT NULL,
SOCIAL_SCIENCE_MAX INT NOT NULL,
COMPUTER_SCIENCE_MAX INT NOT NULL
};